"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { checkIsPublicRoute } from "@/functions/checkIsPublicRoute";
import PrivateRoute from "@/components/PrivateRoute";
import ProviderQuery from "@/components/ProviderQuery";
import ProviderRedux from "@/components/ProviderRedux";
import HeaderPublic from "@/components/HeaderPublic";
import HeaderPrivate from "@/components/HeaderPrivate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();

  const isPublicPage = checkIsPublicRoute(pathName);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProviderQuery>
          <ProviderRedux>
            {isPublicPage ? <HeaderPublic /> : <HeaderPrivate />}
            {isPublicPage ? children : <PrivateRoute> {children} </PrivateRoute>}
          </ProviderRedux>
        </ProviderQuery>
        
      </body>
    </html>
  );
}
